name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Тип сборки (dev/prod)'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - prod
      deploy:
        description: 'Деплой (yes/no)'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm test -- --coverage > coverage.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage.txt

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Load environment variables
        run: cp .env.${{ github.event.inputs.build_type }} .env

      - name: Build project
        run: npm run build --if-present
        env:
          BUILD_TYPE: ${{ github.event.inputs.build_type }}

  docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Documentation
        run: npm run docs

      - name: Deploy Docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs

  deploy:
    needs: build
    if: github.event.inputs.deploy == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        run: echo "Deploying to production..."

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=CI/CD Status: ${{ job.status }} for commit ${{ github.sha }}"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage.txt