name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Тип сборки (dev/prod)'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - prod
      deploy:
        description: 'Деплой (yes/no)'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm test -- --coverage

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present
        env:
          BUILD_TYPE: ${{ github.event.inputs.build_type }}

  deploy:
    needs: build
    if: github.event.inputs.deploy == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        run: echo "Deploying to production..."
